### ISSUE TITLE
"+" Character

### ISSUE THREAD

**Issue by ericklborges** [unitag/QRCODES-API#13]
Hello, 

I am developing a solution using vCard 4.0 text formatting to share contact information.

One of the fields of a vCard is a phone number, which contais a "+" caracter followed by the country code. (e.g. +55 11960574949, +55 for Brazil)

The problem I'm having is that the url encoding takes "+"s as spaces, but I have to incorporate a "+" in to the QR Code.

Do you have any workaround for that?

Maybe a "\+" would be interpreted as a "+"?

Thank You,

Erick Borges

**Comment by spaniernathan** [comment]
Try to urlencode your '+' char.
"+" sign become %2B when URL encoded
