### ISSUE TITLE
Issue coding text type QRCode

### ISSUE THREAD

**Issue by 2ndGAB** [unitag/QRCODES-API#5]
Hello,
I'm trying to make a Text QRCode, so I URLEncode it as needed to pass to the request .

So the original string is `/8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw=` which is encoded to give `%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D`

And when I read the generated QRCode I read `%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D` which means that the given string is decoded before creating the QRCode.

**Comment by AlexisLaporte** [comment]
Hello

Here is a call for the QR Code containing the data you want (/8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw=).

`http://api.qrcode.unitag.fr/api?t_pwd=degraded&setting={%22BODY_TYPE%22:2,%22LAYOUT%22:{%22COLORBG%22:%22ffffff%22,%22COLOR1%22:%22111111%22}}&data={%22DATA%22:{%22TEXT%22:%22%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D%22},%22TYPE%22:%22text%22}`

Regards - Alexis.

**Comment by 2ndGAB** [comment]
Hi Alexis,
This is what I do and it doesn't work as expected. As I said, the QRCode is generated with `%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D` instead of `/8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw=`.

**Comment by AlexisLaporte** [comment]
As I can see when I decode the QR Code, it does contain the unencoded data:
`/8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw=` 

You can see the raw content of a QR Code by using the following tool provided by ZXing: https://zxing.org/w/decode

Alexis.

**Comment by 2ndGAB** [comment]
I don't agree Alexis,

So here is what I do exactly  

```
$data = '%7B%22DATA%22%3A%7B%22TEXT%22%3A%22%252F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%253D%22%7D%2C%22TYPE%22%3A%22TEXT%22%7D';
$setting = '%7B%22E%22%3A%22M%22%2C%22BODY_TYPE%22%3A6%2C%22SIZE%22%3A3000%2C%22LAYOUT%22%3A%7B%22COLOR1%22%3A%22B4214D%22%7D%2C%22EYES%22%3A%7B%22COLOR_EHG%22%3A%22313131%22%2C%22COLOR_EHD%22%3A%22313131%22%2C%22COLOR_EBG%22%3A%22313131%22%2C%22EYE_TYPE%22%3A%22Spike%22%7D%2C%22LOGO%22%3A%7B%22L_NAME%22%3A%22http%3A%2F%2Fdev.2ndguide.fr%2Fimg%2Flock_450x450.png%22%2C%22EXCAVATE%22%3Atrue%7D%2C%22TEXT%22%3A%7B%22LABEL%22%3A%22D%C3%A9blocage+Le+Train+%C3%80+Vapeur+Des+C%C3%A9vennes%22%2C%22COLOR%22%3A%22B4214D%22%2C%22SIZE%22%3A100%2C%22POSITION%22%3A%22CENTER%22%2C%22STYLES%22%3A%22BOLD%22%2C%22QRMARGIN%22%3A100%2C%22SPACING%22%3A100%7D%7D';

$response = Unirest\Request::get($url . 'data=' . $data . '&setting=' . $setting,
    array(
        "X-Mashape-Key" => $myKey
    )
);
```

And the readed QRCode is: `%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D`

**Comment by AlexisLaporte** [comment]
The API works as requested since the data you enter `%7B%22DATA%22%3A%7B%22TEXT%22%3A%22%252F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%253D%22%7D%2C%22TYPE%22%3A%22TEXT%22%7D` translates to `{"DATA":{"TEXT":"%2F8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3D"},"TYPE":"TEXT"}`

There is no need to double encode the content inside the JSON.
`{"DATA":{"TEXT":"/8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw="},"TYPE":"text"}` translates to `%7b%22DATA%22%3a%7b%22TEXT%22%3a%22%2f8MEm12x0XSrO333REoKMwHQJEIVqENPsHFNqLY3pGw%3d%22%7d%2c%22TYPE%22%3a%22text%22%7d`

You can use https://urldecode.org to see the ouput of a URL encoding.

Regards,
Alexis.

**Comment by 2ndGAB** [comment]
Ah ok, You right, that was the problem.
Thanks a lot

**Comment by AlexisLaporte** [comment]
You're welcome
