### ISSUE TITLE
Is this API still maintained?

### ISSUE THREAD

**Issue by 2ndGAB** [unitag/QRCODES-API#6]
Hello,
I'm a bit confused about Unitag-API as the technical support recently redirected me to https://market.mashape.com/unitag/custom-qr-code/

So what should we use?

**Comment by AlexisLaporte** [comment]
Hello,

Please log into Mashape to use our API. Authentication and quota management is easier for you and for us.

The API is the same, so is the documentation.

Alexis.

**Comment by 2ndGAB** [comment]
Ok Alexis,
And so the bug is the same as exposed (here)[https://github.com/unitag/QRCODES-API/issues/5#issuecomment-221191733]
